services:
  postgres:
    image: postgres:17-bullseye
    container_name: pgi_postgres
    restart: always
    shm_size: 128mb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pgi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pgi_test
