# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.7
          - 3.0
    env:
      RACK_ENV: test
    steps:
    - name: Checkout source Code
      uses: actions/checkout@v2
    - name: Setup PostgreSQL server
      uses: harmon758/postgresql-action@v1
      with:
        postgresql version: '13'
        postgresql db: storage_test
        postgresql user: storage
        postgresql password: password
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake test
